# Generated by Django 3.1.2 on 2021-09-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144, unique=True)),
                ('image', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['published_date'],
            },
        ),
    ]
