# Generated by Django 3.1.2 on 2021-09-05 20:55

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
