# Generated by Django 3.1.2 on 2021-09-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20210907_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='catergory',
            field=models.CharField(default='Misc', max_length=144),
        ),
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.CharField(default='Misc', max_length=300),
        ),
    ]
