# Generated by Django 3.1.2 on 2021-09-08 00:12

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20210907_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
