# Generated by Django 3.1.2 on 2021-09-09 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0007_auto_20210908_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='tags',
            field=models.ManyToManyField(related_name='artworks', to='artist.Tag'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
    ]
