# Generated by Django 3.1.2 on 2021-09-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_auto_20210909_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='*No Content', max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='*No Title', max_length=300),
        ),
    ]
