# Generated by Django 3.1.2 on 2021-09-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0011_auto_20210909_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isInChat',
            field=models.BooleanField(default=False),
        ),
    ]
