# Generated by Django 3.1.2 on 2021-09-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_profile_isinchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='isInChat',
            new_name='is_in_Chat',
        ),
    ]
