# Generated by Django 3.1.2 on 2021-09-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0014_auto_20210909_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='MFA_code',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
