# Generated by Django 3.1.2 on 2021-09-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0019_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
